---

- name: "extract artifact"
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: "Install npm and start"
  become: yes
  shell: |
    cd ~/backend
    npm install
    pm2 stop default
    pm2 start npm -- start