---

- name: "extract artifact"
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: "start npm"
  become: yes
  shell: |
    cd /home/ubuntu/backend
    npm install
    npm run build 
    cat .env    

- name: "start application"
  become: yes
  shell: |
    cd ~/backend
    pm2 stop default
    pm2 start npm -- start
    cd dist
    pm2 start main.js
